[package]
name = "personal_log"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.37.0"
clap = { version = "4.5.40", features = ["derive"] }
chrono = "0.4.42"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
csv = "1.3" 
